import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { toast } from 'sonner';
import ReactMarkdown from 'react-markdown';
import { ArrowRight, Loader2, Save, Eye, EyeOff, Plus, Check } from 'lucide-react';
import { airtableFetch, airtableCreate, airtableUpdate, airtableGetFieldChoices } from '@/api/airtable';
import { useAuth } from '@/auth/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';

interface FormState {
  title: string;
  yearNum: string;
  categories: string;   // single-select
  tags: string[];       // multi-select
  status: string;
  readTime: string;
  abstract: string;
  fullContent: string;
  pdfUrl: string;
  keyPoints: string;    // one per line
  sources: string;
}

const EMPTY_FORM: FormState = {
  title: '', yearNum: '',
  categories: '', tags: [], status: 'לא פעיל', readTime: '', abstract: '',
  fullContent: '', pdfUrl: '', keyPoints: '', sources: '',
};

function extractField(val: any): string {
  if (!val) return '';
  if (typeof val === 'string') return val.trim();
  if (typeof val === 'object' && val.value != null) return String(val.value).trim();
  return '';
}

export default function ArticleFormPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const isEdit = !!id;

  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [linkId, setLinkId] = useState('');
  const [createdByName, setCreatedByName] = useState('');
  const [updatedByName, setUpdatedByName] = useState('');
  const [gregYearOptions, setGregYearOptions] = useState<string[]>([]);
  const [categoryOptions, setCategoryOptions] = useState<string[]>([]);
  const [tagOptions, setTagOptions] = useState<string[]>([]);
  const [addingCategory, setAddingCategory] = useState(false);
  const [newCategoryInput, setNewCategoryInput] = useState('');
  const [addingTag, setAddingTag] = useState(false);
  const [newTagInput, setNewTagInput] = useState('');

  useEffect(() => {
    const tasks: Promise<any>[] = [
      airtableGetFieldChoices('מאמרים', 'שנה לועזית'),
      airtableGetFieldChoices('מאמרים', 'קטגוריות'),
      airtableGetFieldChoices('מאמרים', 'תגיות'),
    ];
    if (isEdit) {
      tasks.push(airtableFetch('מאמרים'));
      tasks.push(airtableFetch('משתמשים'));
    }

    Promise.all(tasks)
      .then(([gregChoices, catChoices, tagChoices, articlesData, usersData]) => {
        setGregYearOptions(gregChoices);
        setCategoryOptions(catChoices);
        setTagOptions(tagChoices);
        if (!isEdit || !articlesData) return;

        const record = articlesData.records.find((r: any) => r.id === id);
        if (!record) { toast.error('המאמר לא נמצא'); return; }
        const f = record.fields;

        // Resolve linked user names
        const userRecords: any[] = usersData?.records ?? [];
        const getUserName = (ids: any) => {
          if (!Array.isArray(ids) || !ids.length) return '';
          return userRecords.find((r: any) => r.id === ids[0])?.fields['שם'] ?? '';
        };
        setCreatedByName(getUserName(f['נוצר על ידי']));
        setUpdatedByName(getUserName(f['עודכן על ידי']));

        setLinkId(extractField(f['מזהה קישור']));
        setForm({
          title: extractField(f['כותרת']),
          yearNum: String(f['שנה לועזית'] ?? ''),
          categories: Array.isArray(f['קטגוריות']) ? (f['קטגוריות'][0] ?? '') : extractField(f['קטגוריות']),
          tags: Array.isArray(f['תגיות']) ? f['תגיות'] : [],
          status: extractField(f['סטטוס']) || 'לא פעיל',
          readTime: extractField(f['זמן קריאה']),
          abstract: extractField(f['תקציר']),
          fullContent: extractField(f['תוכן מלא']),
          pdfUrl: extractField(f['קישור PDF']),
          keyPoints: extractField(f['נקודות מפתח']),
          sources: extractField(f['מקורות']),
        });
      })
      .catch(() => toast.error('שגיאה בטעינת נתונים'))
      .finally(() => setLoading(false));
  }, [id]);

  function field(key: keyof FormState, val: string | string[]) {
    setForm(f => ({ ...f, [key]: val }));
  }

  async function handleSave() {
    if (!form.title.trim()) { toast.error('כותרת היא שדה חובה'); return; }
    setSaving(true);
    try {
      // תקציר and זמן קריאה are AI-generated by Airtable — never written via API
      // Only include fields that have actual values — Airtable rejects empty strings
      // for URL / select / number field types
      const fields: Record<string, unknown> = {
        'כותרת': form.title.trim(),
      };

      if (form.fullContent.trim()) fields['תוכן מלא']    = form.fullContent.trim();
      if (form.pdfUrl.trim())      fields['קישור PDF']   = form.pdfUrl.trim();
      if (form.keyPoints.trim())   fields['נקודות מפתח'] = form.keyPoints.trim();
      if (form.sources.trim())     fields['מקורות']       = form.sources.trim();
      if (form.categories)         fields['קטגוריות']    = form.categories;
      fields['סטטוס'] = form.status;
      if (form.tags.length)        fields['תגיות']        = form.tags;
      if (form.yearNum.trim()) {
        // שנה לועזית is a select field → send as array; fall back to number if no choices
        fields['שנה לועזית'] = gregYearOptions.length
          ? [form.yearNum.trim()]
          : parseInt(form.yearNum);
      }

      if (user?.id) fields['עודכן על ידי'] = [user.id];

      if (isEdit) {
        await airtableUpdate('מאמרים', id!, fields);
        toast.success('המאמר עודכן');
      } else {
        if (user?.id) fields['נוצר על ידי'] = [user.id];
        await airtableCreate('מאמרים', fields);
        toast.success('המאמר נוסף');
      }
      navigate('/admin/articles');
    } catch {
      toast.error('שגיאה בשמירה');
    } finally {
      setSaving(false);
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-24">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <Button variant="ghost" size="sm" asChild className="gap-1.5 text-muted-foreground">
          <Link to="/admin/articles">
            <ArrowRight className="h-4 w-4" />
            חזרה
          </Link>
        </Button>
        <div className="w-px h-5 bg-border" />
        <h1 className="text-xl font-bold text-primary flex-1">
          {isEdit ? 'עריכת מאמר' : 'מאמר חדש'}
        </h1>
        <Button onClick={handleSave} disabled={saving} className="bg-secondary text-primary hover:bg-secondary/90 gap-2 min-h-[44px]">
          {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
          {saving ? 'שומר...' : 'שמור'}
        </Button>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-5 gap-6">

        {/* Metadata — left sidebar */}
        <div className="lg:col-span-2 space-y-4">
          <div className="bg-white rounded-xl border border-border p-5 space-y-4">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">פרטי מאמר</p>

            <div className="space-y-1.5">
              <Label>כותרת *</Label>
              <Input value={form.title} onChange={e => field('title', e.target.value)}
                placeholder="כותרת המאמר"
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
            </div>

            <div className="space-y-1.5">
              <Label>סטטוס</Label>
              <div className="flex gap-2">
                {['פעיל', 'לא פעיל'].map(s => (
                  <button
                    key={s}
                    type="button"
                    onClick={() => field('status', s)}
                    className={cn(
                      'flex-1 py-2 rounded-lg border text-sm font-medium transition-all',
                      form.status === s
                        ? s === 'פעיל'
                          ? 'bg-green-600 text-white border-green-600'
                          : 'bg-primary text-white border-primary'
                        : 'bg-white text-muted-foreground border-border hover:border-primary'
                    )}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>

            {isEdit && form.abstract && (
              <div className="space-y-1.5">
                <Label>תקציר</Label>
                <div className="px-3 py-2 rounded-md border border-border bg-muted text-sm text-muted-foreground leading-relaxed">
                  {form.abstract}
                </div>
                <p className="text-xs text-muted-foreground">נוצר אוטומטית על ידי AI</p>
              </div>
            )}

            <div className="space-y-1.5">
              <Label>שנה לועזית</Label>
              {gregYearOptions.length > 0 ? (
                <select
                  value={form.yearNum}
                  onChange={e => field('yearNum', e.target.value)}
                  className="w-full rounded-md border border-input bg-white px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:border-secondary"
                  dir="ltr"
                >
                  <option value="">בחר שנה</option>
                  {gregYearOptions.map(y => (
                    <option key={y} value={y}>{y}</option>
                  ))}
                </select>
              ) : (
                <Input value={form.yearNum} onChange={e => field('yearNum', e.target.value)}
                  placeholder="2024" type="number" dir="ltr"
                  className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
              )}
            </div>

            <div className="space-y-1.5">
              <Label>קטגוריות</Label>
              <div className="flex flex-wrap gap-2">
                {categoryOptions.map(cat => (
                  <button
                    key={cat}
                    type="button"
                    onClick={() => field('categories', form.categories === cat ? '' : cat)}
                    className={cn(
                      'px-3 py-1.5 rounded-full border text-sm font-medium transition-all',
                      form.categories === cat
                        ? 'bg-primary text-white border-primary'
                        : 'bg-white text-muted-foreground border-border hover:border-primary'
                    )}
                  >
                    {cat}
                  </button>
                ))}
                {!addingCategory && (
                  <button
                    type="button"
                    onClick={() => { setAddingCategory(true); setNewCategoryInput(''); }}
                    className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full border border-dashed border-border text-sm text-muted-foreground hover:border-primary hover:text-primary transition-all"
                  >
                    <Plus className="h-3.5 w-3.5" />
                    חדשה
                  </button>
                )}
              </div>
              {addingCategory && (
                <div className="flex gap-2 mt-1">
                  <Input
                    autoFocus
                    value={newCategoryInput}
                    onChange={e => setNewCategoryInput(e.target.value)}
                    placeholder="שם הקטגוריה החדשה..."
                    className="flex-1 border border-secondary bg-white focus-visible:ring-1 focus-visible:border-secondary"
                    onKeyDown={e => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        if (newCategoryInput.trim()) {
                          setCategoryOptions(prev => [...prev, newCategoryInput.trim()]);
                          field('categories', newCategoryInput.trim());
                          setAddingCategory(false);
                        }
                      }
                    }}
                  />
                  <button
                    type="button"
                    onClick={() => {
                      if (newCategoryInput.trim()) {
                        setCategoryOptions(prev => [...prev, newCategoryInput.trim()]);
                        field('categories', newCategoryInput.trim());
                      }
                      setAddingCategory(false);
                    }}
                    className="inline-flex items-center px-3 h-10 rounded-md border border-secondary bg-white text-sm text-primary hover:bg-secondary/10 transition-colors"
                  >
                    <Check className="h-4 w-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => setAddingCategory(false)}
                    className="inline-flex items-center px-3 h-10 rounded-md border border-input bg-white text-sm text-muted-foreground hover:text-primary transition-colors"
                  >
                    ביטול
                  </button>
                </div>
              )}
              {addingCategory && (
                <p className="text-xs text-muted-foreground">הקטגוריה תיווסף אוטומטית לרשימה בעת השמירה</p>
              )}
            </div>

            <div className="space-y-1.5">
              <Label>תגיות</Label>
              <div className="flex flex-wrap gap-2">
                {tagOptions.map(tag => {
                  const selected = form.tags.includes(tag);
                  return (
                    <button
                      key={tag}
                      type="button"
                      onClick={() =>
                        field('tags', selected
                          ? form.tags.filter(t => t !== tag)
                          : [...form.tags, tag]
                        )
                      }
                      className={cn(
                        'px-3 py-1.5 rounded-full border text-sm font-medium transition-all',
                        selected
                          ? 'bg-secondary text-primary border-secondary'
                          : 'bg-white text-muted-foreground border-border hover:border-secondary'
                      )}
                    >
                      {tag}
                    </button>
                  );
                })}
                {!addingTag && (
                  <button
                    type="button"
                    onClick={() => { setAddingTag(true); setNewTagInput(''); }}
                    className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full border border-dashed border-border text-sm text-muted-foreground hover:border-secondary hover:text-primary transition-all"
                  >
                    <Plus className="h-3.5 w-3.5" />
                    חדשה
                  </button>
                )}
              </div>
              {addingTag && (
                <div className="flex gap-2 mt-1">
                  <Input
                    autoFocus
                    value={newTagInput}
                    onChange={e => setNewTagInput(e.target.value)}
                    placeholder="שם התגית החדשה..."
                    className="flex-1 border border-secondary bg-white focus-visible:ring-1 focus-visible:border-secondary"
                    onKeyDown={e => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        const t = newTagInput.trim();
                        if (t && !form.tags.includes(t)) {
                          if (!tagOptions.includes(t)) setTagOptions(prev => [...prev, t]);
                          field('tags', [...form.tags, t]);
                        }
                        setAddingTag(false);
                      }
                    }}
                  />
                  <button
                    type="button"
                    onClick={() => {
                      const t = newTagInput.trim();
                      if (t && !form.tags.includes(t)) {
                        if (!tagOptions.includes(t)) setTagOptions(prev => [...prev, t]);
                        field('tags', [...form.tags, t]);
                      }
                      setAddingTag(false);
                    }}
                    className="inline-flex items-center px-3 h-10 rounded-md border border-secondary bg-white text-sm text-primary hover:bg-secondary/10 transition-colors"
                  >
                    <Check className="h-4 w-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => setAddingTag(false)}
                    className="inline-flex items-center px-3 h-10 rounded-md border border-input bg-white text-sm text-muted-foreground hover:text-primary transition-colors"
                  >
                    ביטול
                  </button>
                </div>
              )}
              {addingTag && (
                <p className="text-xs text-muted-foreground">התגית תיווסף אוטומטית לרשימה בעת השמירה</p>
              )}
            </div>

            {isEdit && form.readTime && (
              <div className="space-y-1.5">
                <Label>זמן קריאה</Label>
                <div className="px-3 py-2 rounded-md border border-border bg-muted text-sm text-muted-foreground font-mono">
                  {form.readTime}
                </div>
                <p className="text-xs text-muted-foreground">נוצר אוטומטית על ידי AI</p>
              </div>
            )}

            <div className="space-y-1.5">
              <Label>קישור PDF</Label>
              <Input value={form.pdfUrl} onChange={e => field('pdfUrl', e.target.value)}
                placeholder="https://..." dir="ltr"
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
            </div>

            <div className="space-y-1.5">
              <Label>נקודות מפתח</Label>
              <Textarea value={form.keyPoints} onChange={e => field('keyPoints', e.target.value)}
                placeholder="נקודה אחת בכל שורה..." rows={4}
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary resize-none" />
              <p className="text-xs text-muted-foreground">נקודה אחת בכל שורה</p>
            </div>

            <div className="space-y-1.5">
              <Label>מקורות</Label>
              <Textarea value={form.sources} onChange={e => field('sources', e.target.value)}
                placeholder="מקורות ומראי מקום..." rows={3}
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary resize-none" />
            </div>

            {isEdit && linkId && (
              <div className="space-y-1.5">
                <Label>מזהה קישור</Label>
                <div className="px-3 py-2 rounded-md border border-border bg-muted text-sm text-muted-foreground font-mono" dir="ltr">
                  {linkId}
                </div>
                <p className="text-xs text-muted-foreground">שדה זה נוצר אוטומטית</p>
              </div>
            )}

            {isEdit && (createdByName || updatedByName) && (
              <div className="pt-3 border-t border-border space-y-2">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">מעקב שינויים</p>
                {createdByName && (
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">נוצר על ידיי</span>
                    <span className="font-medium text-primary">{createdByName}</span>
                  </div>
                )}
                {updatedByName && (
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">עודכן על ידי</span>
                    <span className="font-medium text-primary">{updatedByName}</span>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Content editor — right */}
        <div className="lg:col-span-3">
          <div className="bg-white rounded-xl border border-border overflow-hidden">
            {/* Editor toolbar */}
            <div className="flex items-center justify-between px-5 py-3 border-b border-border">
              <p className="text-sm font-semibold text-primary">תוכן מלא</p>
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground">Markdown</span>
                <Button
                  variant="ghost"
                  size="sm"
                  className="gap-1.5 text-xs"
                  onClick={() => setShowPreview(v => !v)}
                >
                  {showPreview ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
                  {showPreview ? 'הסתר תצוגה מקדימה' : 'הצג תצוגה מקדימה'}
                </Button>
              </div>
            </div>

            {showPreview ? (
              /* Split: editor + preview */
              <div className="grid md:grid-cols-2 divide-x divide-x-reverse divide-border">
                <div className="p-4">
                  <Textarea
                    value={form.fullContent}
                    onChange={e => field('fullContent', e.target.value)}
                    placeholder="כתוב תוכן בפורמט Markdown..."
                    className="border-0 focus-visible:ring-0 resize-none font-mono text-sm min-h-[500px] p-0"
                    dir="rtl"
                  />
                </div>
                <div className="p-5 overflow-y-auto max-h-[600px]">
                  <p className="text-xs text-muted-foreground mb-3 font-medium">תצוגה מקדימה</p>
                  {form.fullContent ? (
                    <div className="prose prose-sm !max-w-none prose-headings:font-serif prose-headings:font-bold prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg prose-p:mb-3">
                      <ReactMarkdown>
                        {form.fullContent.replace(/\n(?!\n)/g, '\n\n')}
                      </ReactMarkdown>
                    </div>
                  ) : (
                    <p className="text-sm text-muted-foreground italic">התוכן יופיע כאן...</p>
                  )}
                </div>
              </div>
            ) : (
              /* Editor only */
              <div className="p-4">
                <Textarea
                  value={form.fullContent}
                  onChange={e => field('fullContent', e.target.value)}
                  placeholder="כתוב תוכן בפורמט Markdown...&#10;&#10;## כותרת&#10;&#10;פסקה רגילה עם **טקסט מודגש** ו*נטוי*.&#10;&#10;- פריט ברשימה&#10;- פריט נוסף"
                  className="border-0 focus-visible:ring-0 resize-none font-mono text-sm min-h-[500px] p-0"
                  dir="rtl"
                />
              </div>
            )}

            {/* Word count */}
            <div className="px-5 py-2 border-t border-border bg-muted/30">
              <p className="text-xs text-muted-foreground">
                {form.fullContent.length > 0
                  ? `${form.fullContent.split(/\s+/).filter(Boolean).length} מילים · ${form.fullContent.length} תווים`
                  : 'לא הוזן תוכן עדיין'
                }
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
