import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { toast } from 'sonner';
import ReactMarkdown from 'react-markdown';
import { ArrowRight, Loader2, Save, Eye, EyeOff } from 'lucide-react';
import { airtableFetch, airtableCreate, airtableUpdate } from '@/api/airtable';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

interface FormState {
  title: string;
  journal: string;
  yeshiva: string;
  yearHebrew: string;
  yearNum: string;
  categories: string;   // comma-separated
  tags: string;         // comma-separated
  readTime: string;
  abstract: string;
  fullContent: string;
  pdfUrl: string;
  keyPoints: string;    // one per line
  sources: string;
}

const EMPTY_FORM: FormState = {
  title: '', journal: '', yeshiva: '', yearHebrew: '', yearNum: '',
  categories: '', tags: '', readTime: '', abstract: '',
  fullContent: '', pdfUrl: '', keyPoints: '', sources: '',
};

function extractField(val: any): string {
  if (!val) return '';
  if (typeof val === 'string') return val.trim();
  if (typeof val === 'object' && val.value != null) return String(val.value).trim();
  return '';
}

export default function ArticleFormPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isEdit = !!id;

  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [loading, setLoading] = useState(isEdit);
  const [saving, setSaving] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [linkId, setLinkId] = useState('');

  useEffect(() => {
    if (!isEdit) return;
    airtableFetch('מאמרים')
      .then(data => {
        const record = data.records.find((r: any) => r.id === id);
        if (!record) { toast.error('המאמר לא נמצא'); return; }
        const f = record.fields;
        setLinkId(extractField(f['מזהה קישור']));
        setForm({
          title: extractField(f['כותרת']),
          journal: extractField(f['כתב עת']),
          yeshiva: extractField(f['מוסד']),
          yearHebrew: extractField(Array.isArray(f['שנה עברית']) ? f['שנה עברית'][0] : f['שנה עברית']),
          yearNum: String(f['שנה לועזית'] ?? ''),
          categories: Array.isArray(f['קטגוריות']) ? f['קטגוריות'].join(', ') : extractField(f['קטגוריות']),
          tags: Array.isArray(f['תגיות']) ? f['תגיות'].join(', ') : extractField(f['תגיות']),
          readTime: extractField(f['זמן קריאה']),
          abstract: extractField(f['תקציר']),
          fullContent: extractField(f['תוכן מלא']),
          pdfUrl: extractField(f['קישור PDF']),
          keyPoints: extractField(f['נקודות מפתח']),
          sources: extractField(f['מקורות']),
        });
      })
      .catch(() => toast.error('שגיאה בטעינת מאמר'))
      .finally(() => setLoading(false));
  }, [id]);

  function field(key: keyof FormState, val: string) {
    setForm(f => ({ ...f, [key]: val }));
  }

  async function handleSave() {
    if (!form.title.trim()) { toast.error('כותרת היא שדה חובה'); return; }
    setSaving(true);
    try {
      const categoriesArr = form.categories.split(',').map(s => s.trim()).filter(Boolean);
      const tagsArr = form.tags.split(',').map(s => s.trim()).filter(Boolean);

      // תקציר and זמן קריאה are AI-generated by Airtable — never written via API
      const fields: Record<string, unknown> = {
        'כותרת': form.title.trim(),
        'כתב עת': form.journal.trim(),
        'מוסד': form.yeshiva.trim(),
        'תוכן מלא': form.fullContent.trim(),
        'קישור PDF': form.pdfUrl.trim(),
        'נקודות מפתח': form.keyPoints.trim(),
        'מקורות': form.sources.trim(),
      };

      if (categoriesArr.length) fields['קטגוריות'] = categoriesArr;
      if (tagsArr.length) fields['תגיות'] = tagsArr;
      if (form.yearNum) fields['שנה לועזית'] = parseInt(form.yearNum);
      if (form.yearHebrew) fields['שנה עברית'] = form.yearHebrew.trim();

      if (isEdit) {
        await airtableUpdate('מאמרים', id!, fields);
        toast.success('המאמר עודכן');
      } else {
        await airtableCreate('מאמרים', fields);
        toast.success('המאמר נוסף');
      }
      navigate('/admin/articles');
    } catch {
      toast.error('שגיאה בשמירה');
    } finally {
      setSaving(false);
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-24">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <Button variant="ghost" size="sm" asChild className="gap-1.5 text-muted-foreground">
          <Link to="/admin/articles">
            <ArrowRight className="h-4 w-4" />
            חזרה
          </Link>
        </Button>
        <div className="w-px h-5 bg-border" />
        <h1 className="text-xl font-bold text-primary flex-1">
          {isEdit ? 'עריכת מאמר' : 'מאמר חדש'}
        </h1>
        <Button onClick={handleSave} disabled={saving} className="bg-secondary text-primary hover:bg-secondary/90 gap-2 min-h-[44px]">
          {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
          {saving ? 'שומר...' : 'שמור'}
        </Button>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-5 gap-6">

        {/* Metadata — left sidebar */}
        <div className="lg:col-span-2 space-y-4">
          <div className="bg-white rounded-xl border border-border p-5 space-y-4">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">פרטי מאמר</p>

            <div className="space-y-1.5">
              <Label>כותרת *</Label>
              <Input value={form.title} onChange={e => field('title', e.target.value)}
                placeholder="כותרת המאמר"
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
            </div>

            {isEdit && form.abstract && (
              <div className="space-y-1.5">
                <Label>תקציר</Label>
                <div className="px-3 py-2 rounded-md border border-border bg-muted text-sm text-muted-foreground leading-relaxed">
                  {form.abstract}
                </div>
                <p className="text-xs text-muted-foreground">נוצר אוטומטית על ידי AI</p>
              </div>
            )}

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>שנה לועזית</Label>
                <Input value={form.yearNum} onChange={e => field('yearNum', e.target.value)}
                  placeholder="2024" type="number" dir="ltr"
                  className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
              </div>
              <div className="space-y-1.5">
                <Label>שנה עברית</Label>
                <Input value={form.yearHebrew} onChange={e => field('yearHebrew', e.target.value)}
                  placeholder="תשפ״ה"
                  className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
              </div>
            </div>

            <div className="space-y-1.5">
              <Label>כתב עת</Label>
              <Input value={form.journal} onChange={e => field('journal', e.target.value)}
                placeholder="שם כתב העת"
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
            </div>

            <div className="space-y-1.5">
              <Label>מוסד</Label>
              <Input value={form.yeshiva} onChange={e => field('yeshiva', e.target.value)}
                placeholder="שם המוסד"
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
            </div>

            <div className="space-y-1.5">
              <Label>קטגוריות</Label>
              <Input value={form.categories} onChange={e => field('categories', e.target.value)}
                placeholder="הלכה, מועדים, תפילה..."
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
              <p className="text-xs text-muted-foreground">מופרדות בפסיק</p>
            </div>

            <div className="space-y-1.5">
              <Label>תגיות</Label>
              <Input value={form.tags} onChange={e => field('tags', e.target.value)}
                placeholder="שבת, ברכות..."
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
              <p className="text-xs text-muted-foreground">מופרדות בפסיק</p>
            </div>

            {isEdit && form.readTime && (
              <div className="space-y-1.5">
                <Label>זמן קריאה</Label>
                <div className="px-3 py-2 rounded-md border border-border bg-muted text-sm text-muted-foreground font-mono">
                  {form.readTime}
                </div>
                <p className="text-xs text-muted-foreground">נוצר אוטומטית על ידי AI</p>
              </div>
            )}

            <div className="space-y-1.5">
              <Label>קישור PDF</Label>
              <Input value={form.pdfUrl} onChange={e => field('pdfUrl', e.target.value)}
                placeholder="https://..." dir="ltr"
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary" />
            </div>

            <div className="space-y-1.5">
              <Label>נקודות מפתח</Label>
              <Textarea value={form.keyPoints} onChange={e => field('keyPoints', e.target.value)}
                placeholder="נקודה אחת בכל שורה..." rows={4}
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary resize-none" />
              <p className="text-xs text-muted-foreground">נקודה אחת בכל שורה</p>
            </div>

            <div className="space-y-1.5">
              <Label>מקורות</Label>
              <Textarea value={form.sources} onChange={e => field('sources', e.target.value)}
                placeholder="מקורות ומראי מקום..." rows={3}
                className="border border-input bg-white focus-visible:ring-1 focus-visible:border-secondary resize-none" />
            </div>

            {isEdit && linkId && (
              <div className="space-y-1.5">
                <Label>מזהה קישור</Label>
                <div className="px-3 py-2 rounded-md border border-border bg-muted text-sm text-muted-foreground font-mono" dir="ltr">
                  {linkId}
                </div>
                <p className="text-xs text-muted-foreground">שדה זה נוצר אוטומטית</p>
              </div>
            )}
          </div>
        </div>

        {/* Content editor — right */}
        <div className="lg:col-span-3">
          <div className="bg-white rounded-xl border border-border overflow-hidden">
            {/* Editor toolbar */}
            <div className="flex items-center justify-between px-5 py-3 border-b border-border">
              <p className="text-sm font-semibold text-primary">תוכן מלא</p>
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground">Markdown</span>
                <Button
                  variant="ghost"
                  size="sm"
                  className="gap-1.5 text-xs"
                  onClick={() => setShowPreview(v => !v)}
                >
                  {showPreview ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
                  {showPreview ? 'הסתר תצוגה מקדימה' : 'הצג תצוגה מקדימה'}
                </Button>
              </div>
            </div>

            {showPreview ? (
              /* Split: editor + preview */
              <div className="grid md:grid-cols-2 divide-x divide-x-reverse divide-border">
                <div className="p-4">
                  <Textarea
                    value={form.fullContent}
                    onChange={e => field('fullContent', e.target.value)}
                    placeholder="כתוב תוכן בפורמט Markdown..."
                    className="border-0 focus-visible:ring-0 resize-none font-mono text-sm min-h-[500px] p-0"
                    dir="rtl"
                  />
                </div>
                <div className="p-5 overflow-y-auto max-h-[600px]">
                  <p className="text-xs text-muted-foreground mb-3 font-medium">תצוגה מקדימה</p>
                  {form.fullContent ? (
                    <div className="prose prose-sm !max-w-none prose-headings:font-serif prose-headings:font-bold prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg prose-p:mb-3">
                      <ReactMarkdown>
                        {form.fullContent.replace(/\n(?!\n)/g, '\n\n')}
                      </ReactMarkdown>
                    </div>
                  ) : (
                    <p className="text-sm text-muted-foreground italic">התוכן יופיע כאן...</p>
                  )}
                </div>
              </div>
            ) : (
              /* Editor only */
              <div className="p-4">
                <Textarea
                  value={form.fullContent}
                  onChange={e => field('fullContent', e.target.value)}
                  placeholder="כתוב תוכן בפורמט Markdown...&#10;&#10;## כותרת&#10;&#10;פסקה רגילה עם **טקסט מודגש** ו*נטוי*.&#10;&#10;- פריט ברשימה&#10;- פריט נוסף"
                  className="border-0 focus-visible:ring-0 resize-none font-mono text-sm min-h-[500px] p-0"
                  dir="rtl"
                />
              </div>
            )}

            {/* Word count */}
            <div className="px-5 py-2 border-t border-border bg-muted/30">
              <p className="text-xs text-muted-foreground">
                {form.fullContent.length > 0
                  ? `${form.fullContent.split(/\s+/).filter(Boolean).length} מילים · ${form.fullContent.length} תווים`
                  : 'לא הוזן תוכן עדיין'
                }
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
